services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_rbac
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: fastapi_rbac_api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@db:5432/fastapi_rbac
      JWT_SECRET_KEY: supersecretkey
      JWT_ALGORITHM: HS256
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data:
